package de.ptrlx.oneshot.contract

import java.io.DataInputStream
import java.io.File
import java.io.InputStream

/**
 * Reads the string constants of compiled classes from the test classpath.
 *
 * Some contract identifiers are private literals inside production classes (the DataStore name, the
 * image and export filename patterns) or live in code generated by Room. Reading the constant pool of
 * the compiled class pins them without changing production code or its visibility.
 */
object ClassFileStrings {

    /** String constants of [clazz] and its nested, inner, anonymous and lambda classes. */
    fun of(clazz: Class<*>): Set<String> = of(clazz.name)

    /** String constants of the class named [className] and its nested, inner, anonymous and lambda classes. */
    fun of(className: String): Set<String> {
        val result = mutableSetOf<String>()
        for (resource in classFiles(className)) {
            val stream = ClassFileStrings::class.java.getResourceAsStream(resource)
                ?: error("Class file $resource not found on the test classpath")
            stream.use { result += readUtf8Constants(it, resource) }
        }
        return result
    }

    private fun classFiles(className: String): List<String> {
        val path = "/" + className.replace('.', '/') + ".class"
        val url = ClassFileStrings::class.java.getResource(path)
            ?: error("Class file $path not found on the test classpath")
        val prefix = path.substringAfterLast('/').removeSuffix(".class") + "$"
        val siblings = if (url.protocol == "file") {
            File(url.toURI()).parentFile
                .listFiles { file -> file.name.startsWith(prefix) && file.name.endsWith(".class") }
                .orEmpty()
                .map { path.substringBeforeLast('/') + "/" + it.name }
        } else {
            generateSequence(1) { it + 1 }
                .map { path.removeSuffix(".class") + "$" + it + ".class" }
                .takeWhile { ClassFileStrings::class.java.getResource(it) != null }
                .toList()
        }
        return listOf(path) + siblings.sorted()
    }

    private fun readUtf8Constants(stream: InputStream, name: String): Set<String> {
        val input = DataInputStream(stream.buffered())
        check(input.readInt() == 0xCAFEBABE.toInt()) { "$name is not a class file" }
        input.readUnsignedShort() // minor version
        input.readUnsignedShort() // major version
        val count = input.readUnsignedShort()
        val strings = mutableSetOf<String>()
        var index = 1
        while (index < count) {
            when (val tag = input.readUnsignedByte()) {
                1 -> strings += input.readUTF() // CONSTANT_Utf8, same encoding as DataInput.readUTF
                3, 4 -> input.skipFully(4) // Integer, Float
                5, 6 -> {
                    input.skipFully(8) // Long, Double take two slots
                    index++
                }
                7, 8, 16, 19, 20 -> input.skipFully(2) // Class, String, MethodType, Module, Package
                9, 10, 11, 12, 17, 18 -> input.skipFully(4) // refs, NameAndType, Dynamic, InvokeDynamic
                15 -> input.skipFully(3) // MethodHandle
                else -> error("Unknown constant pool tag $tag in $name")
            }
            index++
        }
        return strings
    }

    private fun DataInputStream.skipFully(bytes: Int) = readFully(ByteArray(bytes))
}

/**
 * True when the compiled code contains the literal parts of a Kotlin string template such as
 * `"OneShot_$currentDate.jpg"` (parts `OneShot_` and `.jpg`), either as separate constants
 * (StringBuilder concatenation) or as one invokedynamic recipe with `\u0001` placeholders.
 */
fun Set<String>.containsTemplate(vararg parts: String): Boolean =
    parts.all { it in this } ||
        any { constant ->
            constant.contains('\u0001') &&
                constant.split('\u0001').filter { it.isNotEmpty() } == parts.toList()
        }
