package de.ptrlx.oneshot.contract

import java.io.DataInputStream
import java.io.File
import java.io.InputStream
import java.net.JarURLConnection

/**
 * Reads the string constants of compiled classes from the test classpath.
 *
 * Some contract identifiers are private literals inside production classes (the DataStore name, the
 * image and export filename patterns) or live in code generated by Room. Reading the constant pool of
 * the compiled class pins them without changing production code or its visibility.
 */
object ClassFileStrings {

    /**
     * String constants of [clazz], its nested, inner, anonymous and lambda classes, and the Compose
     * live-literal class of its source file.
     *
     * In debug builds the Compose compiler moves Kotlin literals of a file `X.kt` into a generated
     * `LiveLiterals$XKt` class (release builds keep them inline), so that class is read as well.
     * The source file is assumed to be named after the class, as for all classes checked here.
     */
    fun of(clazz: Class<*>): Set<String> = of(clazz.name)

    /** See [of]. */
    fun of(className: String): Set<String> {
        val result = mutableSetOf<String>()
        for (resource in files(className)) {
            val stream = ClassFileStrings::class.java.getResourceAsStream(resource)
                ?: error("Class file $resource not found on the test classpath")
            stream.use { result += readUtf8Constants(it, resource) }
        }
        return result
    }

    /** Class files read for [className]. */
    fun files(className: String): List<String> {
        val path = classPath(className)
        ClassFileStrings::class.java.getResource(path) ?: error("Class file $path not found on the test classpath")
        val liveLiterals = classPath(className.substringBeforeLast('.') + ".LiveLiterals$" + className.substringAfterLast('.') + "Kt")
        return listOf(path) + nestedClasses(path) +
            listOf(liveLiterals).filter { ClassFileStrings::class.java.getResource(it) != null }
    }

    private fun classPath(className: String) = "/" + className.replace('.', '/') + ".class"

    private fun nestedClasses(path: String): List<String> {
        val url = ClassFileStrings::class.java.getResource(path)!!
        val directory = path.substringBeforeLast('/')
        val prefix = path.substringAfterLast('/').removeSuffix(".class") + "$"
        val names = when (url.protocol) {
            "file" -> File(url.toURI()).parentFile.list().orEmpty().toList()
            "jar" -> (url.openConnection() as JarURLConnection).jarFile.entries().asSequence()
                .map { it.name }
                .filter { it.startsWith(directory.removePrefix("/") + "/") }
                .map { it.substringAfterLast('/') }
                .toList()
            else -> error("Cannot list classes next to $url")
        }
        return names.filter { it.startsWith(prefix) && it.endsWith(".class") }.sorted().map { "$directory/$it" }
    }

    private fun readUtf8Constants(stream: InputStream, name: String): Set<String> {
        val input = DataInputStream(stream.buffered())
        check(input.readInt() == 0xCAFEBABE.toInt()) { "$name is not a class file" }
        input.readUnsignedShort() // minor version
        input.readUnsignedShort() // major version
        val count = input.readUnsignedShort()
        val utf8 = arrayOfNulls<String>(count)
        val classNameIndex = IntArray(count)
        var index = 1
        while (index < count) {
            when (val tag = input.readUnsignedByte()) {
                1 -> utf8[index] = input.readUTF() // CONSTANT_Utf8, same encoding as DataInput.readUTF
                7 -> classNameIndex[index] = input.readUnsignedShort() // CONSTANT_Class
                3, 4 -> input.skipFully(4) // Integer, Float
                5, 6 -> {
                    input.skipFully(8) // Long, Double take two slots
                    index++
                }
                8, 16, 19, 20 -> input.skipFully(2) // String, MethodType, Module, Package
                9, 10, 11, 12, 17, 18 -> input.skipFully(4) // refs, NameAndType, Dynamic, InvokeDynamic
                15 -> input.skipFully(3) // MethodHandle
                else -> error("Unknown constant pool tag $tag at index $index in $name")
            }
            index++
        }
        // Self-check: this_class must name the class that was read, otherwise the pool was misparsed.
        input.readUnsignedShort() // access flags
        val thisClass = utf8[classNameIndex[input.readUnsignedShort()]]
        check("/$thisClass.class" == name) { "constant pool of $name misparsed (this_class = $thisClass)" }
        return utf8.filterNotNull().toSet()
    }

    private fun DataInputStream.skipFully(bytes: Int) = readFully(ByteArray(bytes))
}

/**
 * True when the compiled code contains the literal parts of a Kotlin string template such as
 * `"OneShot_$currentDate.jpg"` (parts `OneShot_` and `.jpg`), either as separate constants
 * (StringBuilder concatenation) or as one invokedynamic recipe with `\u0001` placeholders.
 */
fun Set<String>.containsTemplate(vararg parts: String): Boolean =
    parts.all { it in this } ||
        any { constant ->
            constant.contains('\u0001') &&
                constant.split('\u0001').filter { it.isNotEmpty() } == parts.toList()
        }
